### ISSUE TITLE
Clojure 1.7 conflict

### ISSUE THREAD

**Issue by belucid** [cgrand/parsley#15]
When using Parsley under Clojure 1.7 you get:

WARNING: cat already refers to: #'clojure.core/cat in namespace: net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat

I know you put on EOL notice in the README. 

But it gets pulled into a heck of a lot of Clojure projects via this dependency chain:

[midje "1.6.3"]
    [gui-diff "0.5.0"]
        [org.clojars.trptcolin/sjacket "0.1.3" :exclusions [[org.clojure/clojure]]]
            [net.cgrand/parsley "0.9.1"]

**Comment by micha** [comment]
I see this has been fixed in master, could you please release an updated version? Thanks!

**Comment by sritchie** [comment]
Ping!

**Comment by sritchie** [comment]
Would love to see a new version released. If someone'll give me access to the clojars account I'll do it myself, even.

**Comment by belucid** [comment]
+1

**Comment by cgrand** [comment]
Parsley 0.9.3 published

On Thu, Feb 12, 2015 at 8:56 PM, Sean Johnson <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrand/parsley/issues/15#issuecomment-74140794>.
>



-- 
On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by belucid** [comment]
Thanks!
